<a href="https://colab.research.google.com/github/AlexisDesirae/Data-Science-Projects/blob/main/Airline_Satisfaction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Predicting Passanger Airline Satisifaction**

My dataset consists of data collected from an airline satisfaction survey. Data such as gender, age, on-board service, cleanliness, departure delays, etc. are captured in this survey.

I will use this dataset to predict airline satisfaction of different passangers who flew with the airline based on their experience.

I'll start with importing my libraries
*   Pandas- for analyzing data, loading different file objects, deleting columns from the DataFrame
*   Numpy- for handing arrays
*   Seaborn- for data visualization
*   Matplotlib- data visualization
*   Scipy- statistics



In [140]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

import seaborn as sns; sns.set()

Next, I will load my dataset "Airline Customer Satisfaction." I will create a varaiable out of the dataset and name it 'df'

I will use the Head() Method to return the top five rows in my dataset. This will show me each column's name

In [141]:
df = pd.read_csv ('/content/Airline Customer Satisfaction.csv')
df.head()

Unnamed: 0      id  Gender      Customer Type  Age   Type of Travel  \
0           0   70172    Male     Loyal Customer   13  Personal Travel   
1           1    5047    Male  disloyal Customer   25  Business travel   
2           2  110028  Female     Loyal Customer   26  Business travel   
3           3   24026  Female     Loyal Customer   25  Business travel   
4           4  119299    Male     Loyal Customer   61  Business travel   

      Class  Flight Distance  Inflight wifi service  \
0  Eco Plus              460                      3   
1  Business              235                      3   
2  Business             1142                      2   
3  Business              562                      2   
4  Business              214                      3   

   Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                  4  ...                       5   
1                                  2  ...                       1   
2                                  2  ...                       5   
3                                  5  ...                       2   
4                                  3  ...                       3   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 4                 3                 4                4   
1                 1                 5                 3                1   
2                 4                 3                 4                4   
3                 2                 5                 3                1   
4                 3                 4                 4                3   

   Inflight service  Cleanliness  Departure Delay in Minutes  \
0                 5            5                          25   
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   
4                 3            3                           0   

   Arrival Delay in Minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  
4                       0.0                satisfied  

[5 rows x 25 columns]

I will use Info() Method to find out how many entries my dataset has, how many columns, and for insight on each column

In [142]:
df.info

<bound method DataFrame.info of         Unnamed: 0      id  Gender      Customer Type  Age   Type of Travel  \
0                0   70172    Male     Loyal Customer   13  Personal Travel   
1                1    5047    Male  disloyal Customer   25  Business travel   
2                2  110028  Female     Loyal Customer   26  Business travel   
3                3   24026  Female     Loyal Customer   25  Business travel   
4                4  119299    Male     Loyal Customer   61  Business travel   
...            ...     ...     ...                ...  ...              ...   
103899      103899   94171  Female  disloyal Customer   23  Business travel   
103900      103900   73097    Male     Loyal Customer   49  Business travel   
103901      103901   68825    Male  disloyal Customer   30  Business travel   
103902      103902   54173  Female  disloyal Customer   22  Business travel   
103903      103903   62567    Male     Loyal Customer   27  Business travel   

           Class  F

I will use .columns to see which columns will be useful for my analysis and which can be deleted

In [175]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction', 'Class_n', 'satisfaction_n'],
      dtype='object')

I use LabelEncoder to convert the class and satisfaction text into numbers because they are ordinal values and need to be ranked accordingly 

Business class is higher than Econ Plus which is higher than Econ

Satisfied is higher than neutral or dissatisfied

In [144]:
from sklearn.preprocessing import LabelEncoder
le_Class = LabelEncoder()
le_satisfaction = LabelEncoder()

 I will create a new column with the new values and name them 'Class_n' and 'satisfaction_n'

In [145]:
df['Class_n'] = le_Class.fit_transform(df['Class'])
df['satisfaction_n'] = le_satisfaction.fit_transform(df['satisfaction'])

Here I will create a new table with the new class and satisfaction columns and name the new table "satisfaction"

In [146]:
satisfaction = df
satisfaction

Unnamed: 0      id  Gender      Customer Type  Age   Type of Travel  \
0                0   70172    Male     Loyal Customer   13  Personal Travel   
1                1    5047    Male  disloyal Customer   25  Business travel   
2                2  110028  Female     Loyal Customer   26  Business travel   
3                3   24026  Female     Loyal Customer   25  Business travel   
4                4  119299    Male     Loyal Customer   61  Business travel   
...            ...     ...     ...                ...  ...              ...   
103899      103899   94171  Female  disloyal Customer   23  Business travel   
103900      103900   73097    Male     Loyal Customer   49  Business travel   
103901      103901   68825    Male  disloyal Customer   30  Business travel   
103902      103902   54173  Female  disloyal Customer   22  Business travel   
103903      103903   62567    Male     Loyal Customer   27  Business travel   

           Class  Flight Distance  Inflight wifi service  \
0       Eco Plus              460                      3   
1       Business              235                      3   
2       Business             1142                      2   
3       Business              562                      2   
4       Business              214                      3   
...          ...              ...                    ...   
103899       Eco              192                      2   
103900  Business             2347                      4   
103901  Business             1995                      1   
103902       Eco             1000                      1   
103903  Business             1723                      1   

        Departure/Arrival time convenient  ...  Leg room service  \
0                                       4  ...                 3   
1                                       2  ...                 5   
2                                       2  ...                 3   
3                                       5  ...                 5   
4                                       3  ...                 4   
...                                   ...  ...               ...   
103899                                  1  ...                 1   
103900                                  4  ...                 5   
103901                                  1  ...                 2   
103902                                  1  ...                 5   
103903                                  3  ...                 1   

        Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                      4                4                 5            5   
1                      3                1                 4            1   
2                      4                4                 4            5   
3                      3                1                 4            2   
4                      4                3                 3            3   
...                  ...              ...               ...          ...   
103899                 4                2                 3            2   
103900                 5                5                 5            4   
103901                 4                5                 5            4   
103902                 1                5                 4            1   
103903                 4                4                 3            1   

        Departure Delay in Minutes  Arrival Delay in Minutes  \
0                               25                      18.0   
1                                1                       6.0   
2                                0                       0.0   
3                               11                       9.0   
4                                0                       0.0   
...                            ...                       ...   
103899                           3                       0.0   
103900                           0                       0.0   
103901                          

I use get_dummies to differentiate between male and female and personal trip and business trip in a way that does not make it one category seem "better" than another. 

The variables are equal so to treat them as such I use get_dummies which will assign one category the number 0 and the other category the number 1 for both the Gender column and the Type of Travel column

In [147]:
dummies = pd.get_dummies(data=satisfaction, columns=['Gender', 'Type of Travel'])
dummies

Unnamed: 0      id      Customer Type  Age     Class  Flight Distance  \
0                0   70172     Loyal Customer   13  Eco Plus              460   
1                1    5047  disloyal Customer   25  Business              235   
2                2  110028     Loyal Customer   26  Business             1142   
3                3   24026     Loyal Customer   25  Business              562   
4                4  119299     Loyal Customer   61  Business              214   
...            ...     ...                ...  ...       ...              ...   
103899      103899   94171  disloyal Customer   23       Eco              192   
103900      103900   73097     Loyal Customer   49  Business             2347   
103901      103901   68825  disloyal Customer   30  Business             1995   
103902      103902   54173  disloyal Customer   22       Eco             1000   
103903      103903   62567     Loyal Customer   27  Business             1723   

        Inflight wifi service  Departure/Arrival time convenient  \
0                           3                                  4   
1                           3                                  2   
2                           2                                  2   
3                           2                                  5   
4                           3                                  3   
...                       ...                                ...   
103899                      2                                  1   
103900                      4                                  4   
103901                      1                                  1   
103902                      1                                  1   
103903                      1                                  3   

        Ease of Online booking  Gate location  ...  Cleanliness  \
0                            3              1  ...            5   
1                            3              3  ...            1   
2                            2              2  ...            5   
3                            5              5  ...            2   
4                            3              3  ...            3   
...                        ...            ...  ...          ...   
103899                       2              3  ...            2   
103900                       4              4  ...            4   
103901                       1              3  ...            4   
103902                       1              5  ...            1   
103903                       3              3  ...            1   

        Departure Delay in Minutes  Arrival Delay in Minutes  \
0                               25                      18.0   
1                                1                       6.0   
2                                0                       0.0   
3                               11                       9.0   
4                                0                       0.0   
...                            ...                       ...   
103899                           3                       0.0   
103900                           0                       0.0   
103901                           7                      14.0   
103902                           0                       0.0   
103903                           0                       0.0   

                   satisfaction  Class_n  satisfaction_n  Gender_Female  \
0       neutral or dissatisfied        2               0              0   
1       neutral or dissatisfied        0               0              0   
2                     satisfied        0               1              1   
3       neutral or dissatisfied        0               0              1   
4                     satisfied        0               1              0   
...                         ...      ...             ...            ...   
103899  neutral or dissatisfied        1               0              1   
103900                satisfied        0    

Here I will drop all NaN values

In [148]:
dummies.dropna(axis='columns', how='all')

Unnamed: 0      id      Customer Type  Age     Class  Flight Distance  \
0                0   70172     Loyal Customer   13  Eco Plus              460   
1                1    5047  disloyal Customer   25  Business              235   
2                2  110028     Loyal Customer   26  Business             1142   
3                3   24026     Loyal Customer   25  Business              562   
4                4  119299     Loyal Customer   61  Business              214   
...            ...     ...                ...  ...       ...              ...   
103899      103899   94171  disloyal Customer   23       Eco              192   
103900      103900   73097     Loyal Customer   49  Business             2347   
103901      103901   68825  disloyal Customer   30  Business             1995   
103902      103902   54173  disloyal Customer   22       Eco             1000   
103903      103903   62567     Loyal Customer   27  Business             1723   

        Inflight wifi service  Departure/Arrival time convenient  \
0                           3                                  4   
1                           3                                  2   
2                           2                                  2   
3                           2                                  5   
4                           3                                  3   
...                       ...                                ...   
103899                      2                                  1   
103900                      4                                  4   
103901                      1                                  1   
103902                      1                                  1   
103903                      1                                  3   

        Ease of Online booking  Gate location  ...  Cleanliness  \
0                            3              1  ...            5   
1                            3              3  ...            1   
2                            2              2  ...            5   
3                            5              5  ...            2   
4                            3              3  ...            3   
...                        ...            ...  ...          ...   
103899                       2              3  ...            2   
103900                       4              4  ...            4   
103901                       1              3  ...            4   
103902                       1              5  ...            1   
103903                       3              3  ...            1   

        Departure Delay in Minutes  Arrival Delay in Minutes  \
0                               25                      18.0   
1                                1                       6.0   
2                                0                       0.0   
3                               11                       9.0   
4                                0                       0.0   
...                            ...                       ...   
103899                           3                       0.0   
103900                           0                       0.0   
103901                           7                      14.0   
103902                           0                       0.0   
103903                           0                       0.0   

                   satisfaction  Class_n  satisfaction_n  Gender_Female  \
0       neutral or dissatisfied        2               0              0   
1       neutral or dissatisfied        0               0              0   
2                     satisfied        0               1              1   
3       neutral or dissatisfied        0               0              1   
4                     satisfied        0               1              0   
...                         ...      ...             ...            ...   
103899  neutral or dissatisfied        1               0              1   
103900                satisfied        0    

Identify our independent or target variable (y) and our dependent variable(s) X.

To identify our X we must create a table that includes only the dependent variables that we want to test against our independent variable. I used the Drop() Method to drop all of the unnessesary columns and to drop the 'satisfaction' column because that will serve as my y variable. 

In [149]:
X = dummies.drop(['Unnamed: 0', 'id', 'Customer Type','Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient','Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness','satisfaction', 'Gender_Male', 'Type of Travel_Personal Travel', 'Class', 'satisfaction_n','Arrival Delay in Minutes', 'Ease of Online booking'], axis='columns')
X

Age  Inflight service  Departure Delay in Minutes  Class_n  \
0        13                 5                          25        2   
1        25                 4                           1        0   
2        26                 4                           0        0   
3        25                 4                          11        0   
4        61                 3                           0        0   
...     ...               ...                         ...      ...   
103899   23                 3                           3        1   
103900   49                 5                           0        0   
103901   30                 5                           7        0   
103902   22                 4                           0        1   
103903   27                 3                           0        0   

        Gender_Female  Type of Travel_Business travel  
0                   0                               0  
1                   0                               1  
2                   1                               1  
3                   1                               1  
4                   0                               1  
...               ...                             ...  
103899              1                               1  
103900              0                               1  
103901              0                               1  
103902              1                               1  
103903              0                               1  

[103904 rows x 6 columns]

I created a variable and named it 'y' and it includes the 'satisfaction' column which is my independent variable.

In [150]:
y = dummies['satisfaction_n']
y

0         0
1         0
2         1
3         0
4         1
         ..
103899    0
103900    1
103901    0
103902    0
103903    0
Name: satisfaction_n, Length: 103904, dtype: int64

Now we will use train test split to evaluate the performance of each model.

I'll test LinearRegression first so I import LinearRegression from sklearn


In [174]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [153]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

Then I fit the training data with model.fit


In [154]:
model.fit(X_train, y_train)

LinearRegression()

Now I will score my data or test it for accuracy

In [155]:
model.score(X_test, y_test)

0.3188248688919827

 My Linear Regression model is only 31% accurate which is very low. So I will repeat the same process for Random Forest

**Random Forest**

In [159]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [160]:
model.fit(X, y)

RandomForestClassifier()

In [161]:
model.score(X,y)

0.8693794271635356

Random Forest provided a much better accuracy of 87%

Before I begin to predict I need to find out what the minimum and maximum values in each column are so I can predict correctly

I will find out these values using Min() and Max() Methods

In [162]:
min_val = dummies[:].min() 
max_val = dummies[:].max() 

print(max_val)

Unnamed: 0                                      103903
id                                              129880
Customer Type                        disloyal Customer
Age                                                 85
Class                                         Eco Plus
Flight Distance                                   4983
Inflight wifi service                                5
Departure/Arrival time convenient                    5
Ease of Online booking                               5
Gate location                                        5
Food and drink                                       5
Online boarding                                      5
Seat comfort                                         5
Inflight entertainment                               5
On-board service                                     5
Leg room service                                     5
Baggage handling                                     5
Checkin service                                      5
Inflight s

In [163]:
print(min_val)

Unnamed: 0                                                 0
id                                                         1
Customer Type                                 Loyal Customer
Age                                                        7
Class                                               Business
Flight Distance                                           31
Inflight wifi service                                      0
Departure/Arrival time convenient                          0
Ease of Online booking                                     0
Gate location                                              0
Food and drink                                             0
Online boarding                                            0
Seat comfort                                               0
Inflight entertainment                                     0
On-board service                                           0
Leg room service                                           0
Baggage handling        

I want to reorder the columns so that it is easier for me to predict so I call the columns again and reorder them in the order that I'd like them to appear. I name the reordered table 'reorder'

In [164]:
X.columns

Index(['Age', 'Inflight service', 'Departure Delay in Minutes', 'Class_n',
       'Gender_Female', 'Type of Travel_Business travel'],
      dtype='object')

In [165]:
reorder = dummies [['Age', 'Gender_Female', 'Class_n', 'Type of Travel_Business travel','Departure Delay in Minutes', 'Inflight service']]
reorder

Age  Gender_Female  Class_n  Type of Travel_Business travel  \
0        13              0        2                               0   
1        25              0        0                               1   
2        26              1        0                               1   
3        25              1        0                               1   
4        61              0        0                               1   
...     ...            ...      ...                             ...   
103899   23              1        1                               1   
103900   49              0        0                               1   
103901   30              0        0                               1   
103902   22              1        1                               1   
103903   27              0        0                               1   

        Departure Delay in Minutes  Inflight service  
0                               25                 5  
1                                1                 4  
2                                0                 4  
3                               11                 4  
4                                0                 3  
...                            ...               ...  
103899                           3                 3  
103900                           0                 5  
103901                           7                 5  
103902                           0                 4  
103903                           0                 3  

[103904 rows x 6 columns]

Now I'll begin predicting passanger satisfaction with my chosen columns


Remember the new values

Gender: Male is 0 Female is 1 

Type of travel: Business is 0 Personal is 1 

Class: Econ is 0, Econ Plus is 1, Business is 1 

Satisfaction: Neutral or dissatisfied is 0, Satisfied is 1 

**Prediction Time**


Predict the airline satisfication of a **32** year old **male** who flew **Econ** class for a **personal** trip. The flight departed **10 minutes late** and he experienced **okay inflight service** 

In [166]:
model.predict([[32,0,0,1,10,3]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1])

Predict the airline satisfication of a **25** year old **male** who flew **business** class for a **personal** trip. The flight departed **5 minutes late** and he experienced **poor inflight service**

In [167]:
model.predict([[25,0,2,0,5,2]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1])

Predict the airline satisfication of a **8** year old **male** who flew **Econ Plus** for a **personal** trip. The flight departed **45 minutes late** but he experienced **excellent flight service**

In [176]:
model.predict([[8,0,1,0,45,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1])

**From the predictions these older men were satisified with their airline experience despite the poor to okay inflight service. It would behoove me to look into the possibility of their reason for flying (personal travel) and the minimal delay as reasons for still being satisifed despite poor inflight service**

**The young man had a different experience in terms of wait time and level of flight service recieved but he was also satisfied with his experience. His age could play a role in the way he ranked his experience but doesn't necessarily have to**

Predict the airline satisfication of a **47** year old **female** who flew **Econ Plus** class for a **business** trip. The flight departed **25 minutes late** but she experienced **excellent inflight service**

In [168]:
model.predict([[47,1,1,1,25,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

Predict the airline satisfication of a **64** year old **female** who flew **Business** class for a **personal** trip. The flight departed **0 minutes late** and she experienced **good inflight service**

In [169]:
model.predict([[64,1,2,0,0,4]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

Predict the airline satisfication of a **35** year old **female** who flew **Business** class for a **business** trip. The flight departed **5 minutes late** and she experienced **excellent inflight service**

In [171]:
model.predict([[35,1,2,0,5,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

Predict the airline satisfication of a **35** year old **female** who flew **Econ** class for a **business** trip. The flight departed **10 minutes late** and she experienced **okay inflight service**

In [172]:
model.predict([[35,1,0,0,10,3]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

Predict the airline satisfication of a **35** year old **male** who flew **Econ Plus** class for a **business** trip. The flight departed **5 minutes late** but he experienced **good inflight service** 

In [173]:
model.predict([[35,0,1,1,5,4]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

**It is much harder to try to predict why these individuals were unsatisfied with their airline experience. Each individual experienced good to excellent inflight service but that wasn't enough for a satisfactory rating. The ages, genders, reasons for flying, class and departure delays vary which makes it difficult to pinpoint their reason for dissatisfaction**